version: '3'

services:
  django:
    build: .
    env_file:
      - .env_publisher
    tty: true
    links:
      - 'database:db'
    volumes:
      - ./:/app
    entrypoint: /app/entrypoint.sh
    networks:
      - collector
    depends_on:
      - database

  database:
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - .postgresql.conf:/postgresql.conf
    networks:
      - collector
    command: postgres -c config_file=/postgresql.conf


networks:
  collector:
    external: true
